### ISSUE TITLE
broken on python 3.10 ?

### ISSUE THREAD

**Issue by fenugrec** [tpircher-zz/pycrc#46]
```
Traceback (most recent call last):
  File "/usr/bin/pycrc", line 26, in <module>
    from pycrc.main import main
  File "/usr/lib/python3.10/site-packages/pycrc/main.py", line 46, in <module>
    import pycrc.codegen as cg
  File "/usr/lib/python3.10/site-packages/pycrc/codegen.py", line 37, in <module>
    import pycrc.symtable
  File "/usr/lib/python3.10/site-packages/pycrc/symtable.py", line 49, in <module>
    class SymbolTable(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

Looks like collections.MutableMapping was deprecated at some point ?

**Comment by fenugrec** [comment]
Possible fix (I don't actually know what I'm doing) :  two lines to change,


```
from collections.abc import MutableMapping
.....
class SymbolTable(MutableMapping):
```

**Comment by tpircher** [comment]
Sorry for the late answer; I have been locked out from github, and had to create a new account. The fix should be in https://github.com/tpircher/pycrc
